# Generated by Django 2.1.7 on 2019-03-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=45)),
                ('password1', models.CharField(max_length=25)),
                ('password2', models.CharField(max_length=25)),
            ],
        ),
    ]
